server:
  port: 9000
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  application:
    name: api.midni.ru
  devtools:
    livereload:
      port: 90000
  datasource:
    url: jdbc:postgresql://localhost/midni_db
    username: midni_user
    password: 1&8NBD@oBq#&IUpi0x
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update #validate #create-drop
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://midni.eu.auth0.com/

http:
  request-timeout: 5000

auth0:
  audience: https://api.midni.ru
